name: HighspeedWorks
favicon: null
layout_spectrum: 0.16292770160362124
typography_spectrum: 0.38977
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4e637e'
    - '#b1987a'
    - '#88745b'
    - '#f1ca9f'
    - '#180300'
  brandStrength: 0.9321890014689416
  lightness: 0.26382241351529956
  saturation: 0.7364090273622423
  rhythmicContrast: 0.44425602187402546
purpose: []
